CREATE TABLE `User` (
`id` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(25) NOT NULL,
`age` INT(3),
`isAdmin` BIT,
`createDate` TIMESTAMP DEFAULT NOW(),
PRIMARY KEY (`id`))
ENGINE=InnoDB AUTO_INCREMENT=1
DEFAULT CHARSET=utf8;